
/* Array of string literals mapped by numeric code (index == enum value). */
static const char *tio_input_event_code_names[] = {
    "KEY_NULL", /* 0 */
    "CTRL_A", /* 1 */
    "CTRL_B", /* 2 */
    "CTRL_C", /* 3 */
    "CTRL_D", /* 4 */
    "CTRL_E", /* 5 */
    "CTRL_F", /* 6 */
    "CTRL_G", /* 7 */
    "CTRL_H", /* 8 */
    "CTRL_I/TAB", /* 9 */
    "CTRL_J", /* 10 */
    "CTRL_K", /* 11 */
    "CTRL_L", /* 12 */
    "CTRL_M/ENTER", /* 13 */
    "CTRL_N", /* 14 */
    "CTRL_O", /* 15 */
    "CTRL_P", /* 16 */
    "CTRL_Q", /* 17 */
    "CTRL_R", /* 18 */
    "CTRL_S", /* 19 */
    "CTRL_T", /* 20 */
    "CTRL_U", /* 21 */
    "CTRL_V", /* 22 */
    "CTRL_W", /* 23 */
    "CTRL_X", /* 24 */
    "CTRL_Y", /* 25 */
    "CTRL_Z", /* 26 */
    "ESC", /* 27 */
    "UNASSIGNED", /* 28 */
    "UNASSIGNED", /* 29 */
    "UNASSIGNED", /* 30 */
    "UNASSIGNED", /* 31 */
    "SPACE", /* 32 */
    "EXCLAMATION_MARK", /* 33 */
    "DOUBLE_QUOTES", /* 34 */
    "NUMBER_SIGN", /* 35 */
    "DOLLAR", /* 36 */
    "PER_CENT_SIGN", /* 37 */
    "AMPERSAND", /* 38 */
    "SINGLE_QUOTE", /* 39 */
    "OPEN_PARENTHESIS", /* 40 */
    "CLOSE_PARENTHESIS", /* 41 */
    "ASTERISK", /* 42 */
    "PLUS", /* 43 */
    "COMMA", /* 44 */
    "MINUS", /* 45 */
    "PERIOD", /* 46 */
    "FORWARD_SLASH", /* 47 */
    "ZERO", /* 48 */
    "ONE", /* 49 */
    "TWO", /* 50 */
    "THREE", /* 51 */
    "FOUR", /* 52 */
    "FIVE", /* 53 */
    "SIX", /* 54 */
    "SEVEN", /* 55 */
    "EIGHT", /* 56 */
    "NINE", /* 57 */
    "COLON", /* 58 */
    "SEMICOLON", /* 59 */
    "LESS_THAN", /* 60 */
    "EQUALS", /* 61 */
    "GREATER_THAN", /* 62 */
    "QUESTION_MARK", /* 63 */
    "AT_SIGN", /* 64 */
    "UPPERCASE_A", /* 65 */
    "UPPERCASE_B", /* 66 */
    "UPPERCASE_C", /* 67 */
    "UPPERCASE_D", /* 68 */
    "UPPERCASE_E", /* 69 */
    "UPPERCASE_F", /* 70 */
    "UPPERCASE_G", /* 71 */
    "UPPERCASE_H", /* 72 */
    "UPPERCASE_I", /* 73 */
    "UPPERCASE_J", /* 74 */
    "UPPERCASE_K", /* 75 */
    "UPPERCASE_L", /* 76 */
    "UPPERCASE_M", /* 77 */
    "UPPERCASE_N", /* 78 */
    "UPPERCASE_O", /* 79 */
    "UPPERCASE_P", /* 80 */
    "UPPERCASE_Q", /* 81 */
    "UPPERCASE_R", /* 82 */
    "UPPERCASE_S", /* 83 */
    "UPPERCASE_T", /* 84 */
    "UPPERCASE_U", /* 85 */
    "UPPERCASE_V", /* 86 */
    "UPPERCASE_W", /* 87 */
    "UPPERCASE_X", /* 88 */
    "UPPERCASE_Y", /* 89 */
    "UPPERCASE_Z", /* 90 */
    "OPENING_SQUARE_BRACKET", /* 91 */
    "BACKSLASH", /* 92 */
    "CLOSING_SQUARE_BRACKET", /* 93 */
    "CARET", /* 94 */
    "UNDERSCORE", /* 95 */
    "GRAVE_ACCENT", /* 96 */
    "LOWERCASE_A", /* 97 */
    "LOWERCASE_B", /* 98 */
    "LOWERCASE_C", /* 99 */
    "LOWERCASE_D", /* 100 */
    "LOWERCASE_E", /* 101 */
    "LOWERCASE_F", /* 102 */
    "LOWERCASE_G", /* 103 */
    "LOWERCASE_H", /* 104 */
    "LOWERCASE_I", /* 105 */
    "LOWERCASE_J", /* 106 */
    "LOWERCASE_K", /* 107 */
    "LOWERCASE_L", /* 108 */
    "LOWERCASE_M", /* 109 */
    "LOWERCASE_N", /* 110 */
    "LOWERCASE_O", /* 111 */
    "LOWERCASE_P", /* 112 */
    "LOWERCASE_Q", /* 113 */
    "LOWERCASE_R", /* 114 */
    "LOWERCASE_S", /* 115 */
    "LOWERCASE_T", /* 116 */
    "LOWERCASE_U", /* 117 */
    "LOWERCASE_V", /* 118 */
    "LOWERCASE_W", /* 119 */
    "LOWERCASE_X", /* 120 */
    "LOWERCASE_Y", /* 121 */
    "LOWERCASE_Z", /* 122 */
    "OPENING_CURLY_BRACE", /* 123 */
    "VERTICAL_BAR", /* 124 */
    "CLOSING_CURLY_BRACE", /* 125 */
    "TILDE", /* 126 */
    "BACKSPACE", /* 127 */
    "ARROW_UP", /* 128 */
    "ARROW_DOWN", /* 129 */
    "ARROW_RIGHT", /* 130 */
    "ARROW_LEFT", /* 131 */
    "HOME_KEY", /* 132 */
    "END_KEY", /* 133 */
    "CTRL_ARROW_UP", /* 134 */
    "CTRL_ARROW_DOWN", /* 135 */
    "CTRL_ARROW_RIGHT", /* 136 */
    "CTRL_ARROW_LEFT", /* 137 */
    "INSERT_KEY", /* 138 */
    "DEL_KEY", /* 139 */
    "PAGE_UP", /* 140 */
    "PAGE_DOWN", /* 141 */
    "FUNCTION_1", /* 142 */
    "FUNCTION_2", /* 143 */
    "FUNCTION_3", /* 144 */
    "FUNCTION_4", /* 145 */
    "FUNCTION_5", /* 146 */
    "FUNCTION_6", /* 147 */
    "FUNCTION_7", /* 148 */
    "FUNCTION_8", /* 149 */
    "FUNCTION_9", /* 150 */
    "FUNCTION_10", /* 151 */
    "FUNCTION_11", /* 152 */
    "FUNCTION_12", /* 153 */
    "LMB_DOWN", /* 154 */
    "LMB_UP", /* 155 */
    "LMB_PRESSED_MOVE", /* 156 */
    "MMB_DOWN", /* 157 */
    "MMB_UP", /* 158 */
    "MMB_PRESSED_MOVE", /* 159 */
    "RMB_DOWN", /* 160 */
    "RMB_UP", /* 161 */
    "RMB_PRESSED_MOVE", /* 162 */
    "SCROLL_UP", /* 163 */
    "SCROLL_DOWN", /* 164 */
    "MOUSE_MOVE" /* 165 */
};

#define TIO_INPUT_EVENT_CODE_COUNT (sizeof(tio_input_event_code_names) / sizeof(tio_input_event_code_names[0]))

static inline const char *tio_input_event_code_to_string(int code) {
    if (code < 0 || code >= (int)TIO_INPUT_EVENT_CODE_COUNT) return "UNKNOWN";
    return tio_input_event_code_names[code];
}